/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAward: typeof import('./src/components/builder_components/AddAward.vue')['default']
    AddEducation: typeof import('./src/components/builder_components/AddEducation.vue')['default']
    AddExperience: typeof import('./src/components/builder_components/AddExperience.vue')['default']
    AddProject: typeof import('./src/components/builder_components/AddProject.vue')['default']
    AddSkill: typeof import('./src/components/builder_components/AddSkill.vue')['default']
    BadgeEditor: typeof import('./src/components/badge_components/BadgeEditor.vue')['default']
    BadgeList: typeof import('./src/components/badge_components/BadgeList.vue')['default']
    BadgePopUp: typeof import('./src/components/fp_components/BadgePopUp.vue')['default']
    CustomButton: typeof import('./src/components/fp_components/CustomButton.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    EventEditor: typeof import('./src/components/event_components/EventEditor.vue')['default']
    EventList: typeof import('./src/components/event_components/EventList.vue')['default']
    EventStudents: typeof import('./src/components/event_components/EventStudents.vue')['default']
    ExpandedCombo: typeof import('./src/components/fp_edit_components/ExpandedCombo.vue')['default']
    ExpandedEvents: typeof import('./src/components/event_components/ExpandedEvents.vue')['default']
    ExpandedEventsCombo: typeof import('./src/components/event_components/ExpandedEventsCombo.vue')['default']
    ExpandedSemester: typeof import('./src/components/fp_edit_components/ExpandedSemester.vue')['default']
    ExpandedSubmission: typeof import('./src/components/submissionview-components/ExpandedSubmission.vue')['default']
    ExpandedTask: typeof import('./src/components/fp_components/ExpandedTask.vue')['default']
    ExpandedTasks: typeof import('./src/components/fp_edit_components/ExpandedTasks.vue')['default']
    FlightPlanCard: typeof import('./src/components/fp_components/FlightPlanCard.vue')['default']
    FlightPlanSemesterCard: typeof import('./src/components/fp_components/FlightPlanSemesterCard.vue')['default']
    FpManager: typeof import('./src/components/fp_edit_components/FpManager.vue')['default']
    IconRow: typeof import('./src/components/IconRow.vue')['default']
    MonthlyCalendar: typeof import('./src/components/event_components/MonthlyCalendar.vue')['default']
    NewTemplateOverlay: typeof import('./src/components/fp_edit_components/NewTemplateOverlay.vue')['default']
    PreviewImage: typeof import('./src/components/submissionview-components/PreviewImage.vue')['default']
    RedeemableCard: typeof import('./src/components/point-shop-components/RedeemableCard.vue')['default']
    RedeemableCardUser: typeof import('./src/components/point-shop-components/RedeemableCardUser.vue')['default']
    Resume: typeof import('./src/components/Resume.vue')['default']
    ResumePreview: typeof import('./src/components/ResumePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SemesterIcon: typeof import('./src/components/fp_edit_components/SemesterIcon.vue')['default']
    SocialLogin: typeof import('./src/components/SocialLogin.vue')['default']
    StudentAddDialog: typeof import('./src/components/event_components/StudentAddDialog.vue')['default']
    StudentEventCalendar: typeof import('./src/components/event_components/StudentEventCalendar.vue')['default']
    StudentViewEvent: typeof import('./src/components/event_components/StudentViewEvent.vue')['default']
    SubmissionList: typeof import('./src/components/submissionview-components/SubmissionList.vue')['default']
    TaskEditor: typeof import('./src/components/fp_edit_components/TaskEditor.vue')['default']
    TaskList: typeof import('./src/components/fp_edit_components/TaskList.vue')['default']
    TemplatePicker: typeof import('./src/components/TemplatePicker.vue')['default']
    TimeSelector: typeof import('./src/components/fp_edit_components/TimeSelector.vue')['default']
    WeeklyCalendar: typeof import('./src/components/event_components/WeeklyCalendar.vue')['default']
    YearIcon: typeof import('./src/components/fp_edit_components/YearIcon.vue')['default']
  }
}
